name: .NET Build

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"   # change if you're using .NET 6/7

      - name: Restore dependencies
        run: dotnet restore BizApp.sln

      - name: Build
        run: dotnet build BizApp.sln --configuration Release --no-restore
